window.QUESTIONS_M4 = [
  { id: 325, point: "报表", q: "资产负债表中的应收账款项目应按扣除坏账准备后的净额填列。", options: ["正确", "错误"], answer: 0, explain: "应收账款项目反映预期可收回金额，应扣除坏账准备后的净额填列。", subject: "会计", difficulty: "basic", type: "judge" },
  { id: 326, point: "固定资产", q: "固定资产盘盈应直接计入营业外收入。", options: ["正确", "错误"], answer: 1, explain: "固定资产盘盈通常作为重大前期差错处理，通过以前年度损益调整核算。", subject: "会计", difficulty: "advanced", type: "judge" },
  { id: 327, point: "审计目标", q: "财务报表审计对财务报表不存在重大错报提供合理保证。", options: ["正确", "错误"], answer: 0, explain: "财务报表审计提供合理保证，而非绝对保证。", subject: "审计", difficulty: "basic", type: "judge" },
  { id: 328, point: "审计风险", q: "注册会计师可以将审计风险完全消除。", options: ["正确", "错误"], answer: 1, explain: "受审计固有限制影响，审计风险只能降低到可接受水平，无法完全消除。", subject: "审计", difficulty: "advanced", type: "judge" },
  { id: 329, point: "资本预算", q: "净现值大于零的项目通常可以增加股东财富。", options: ["正确", "错误"], answer: 0, explain: "NPV 大于零表示项目未来现金流入现值超过投资成本，通常增加企业价值。", subject: "财管", difficulty: "basic", type: "judge" },
  { id: 330, point: "资本预算", q: "互斥项目评价中，IRR 高于资本成本时一定应选择该项目。", options: ["正确", "错误"], answer: 1, explain: "互斥项目应优先选择 NPV 最大的项目，IRR 与 NPV 可能产生冲突。", subject: "财管", difficulty: "expert", type: "judge" },
  { id: 331, point: "增值税", q: "增值税专用发票是购买方合法抵扣进项税额的重要凭证。", options: ["正确", "错误"], answer: 0, explain: "增值税专用发票是凭票抵扣进项税额的重要合法凭证。", subject: "税法", difficulty: "basic", type: "judge" },
  { id: 332, point: "企业所得税", q: "业务招待费可以全额在企业所得税前扣除。", options: ["正确", "错误"], answer: 1, explain: "业务招待费按发生额的 60% 与销售收入 5‰ 孰低扣除，不能全额扣除。", subject: "税法", difficulty: "advanced", type: "judge" },
  { id: 333, point: "合伙企业法", q: "普通合伙人对合伙企业债务承担无限连带责任。", options: ["正确", "错误"], answer: 0, explain: "普通合伙人应对合伙企业债务承担无限连带责任。", subject: "经济法", difficulty: "basic", type: "judge" },
  { id: 334, point: "公司治理", q: "股份有限公司董事会成员人数没有法定下限。", options: ["正确", "错误"], answer: 1, explain: "现行公司法要求股份有限公司董事会成员为三人以上。", subject: "经济法", difficulty: "advanced", type: "judge" },
  { id: 335, point: "波士顿矩阵", q: "波士顿矩阵中的明星业务具有高市场增长率和高相对市场份额。", options: ["正确", "错误"], answer: 0, explain: "明星业务处于高增长、高份额象限。", subject: "战略", difficulty: "basic", type: "judge" },
  { id: 336, point: "平衡计分卡", q: "平衡计分卡只关注财务维度。", options: ["正确", "错误"], answer: 1, explain: "平衡计分卡包括财务、客户、内部流程、学习与成长四个维度。", subject: "战略", difficulty: "advanced", type: "judge" },
  { id: 337, point: "报表", q: "下列属于资产负债表流动负债项目的有（　）。", options: ["短期借款", "应付账款", "应付债券", "一年内到期的非流动负债"], answer: [0, 1, 3], explain: "短期借款、应付账款和一年内到期的非流动负债通常在一年内偿付；应付债券一般属于非流动负债。", subject: "会计", difficulty: "basic", type: "multiple" },
  { id: 338, point: "报表", q: "下列属于利润表项目的有（　）。", options: ["营业收入", "营业成本", "应收账款", "销售费用"], answer: [0, 1, 3], explain: "营业收入、营业成本和销售费用反映经营成果；应收账款属于资产负债表项目。", subject: "会计", difficulty: "basic", type: "multiple" },
  { id: 339, point: "审计证据", q: "下列通常具有较高可靠性的审计证据包括（　）。", options: ["外部独立来源的书面证据", "直接观察获取的证据", "未经核验的复印件", "内部生成且未经验证的口头陈述"], answer: [0, 1], explain: "外部独立书面证据和直接观察证据可靠性较高；未核验复印件和未验证口头陈述可靠性较低。", subject: "审计", difficulty: "advanced", type: "multiple" },
  { id: 340, point: "审计意见", q: "下列属于非无保留意见类型的有（　）。", options: ["保留意见", "否定意见", "无法表示意见", "带强调事项段的无保留意见"], answer: [0, 1, 2], explain: "非无保留意见包括保留意见、否定意见和无法表示意见；带强调事项段的无保留意见仍属于无保留意见。", subject: "审计", difficulty: "advanced", type: "multiple" },
  { id: 341, point: "资本预算", q: "下列属于资本预算评价方法的有（　）。", options: ["净现值法", "内含报酬率法", "回收期法", "存货周转率法"], answer: [0, 1, 2], explain: "净现值法、内含报酬率法和回收期法用于投资项目评价；存货周转率属于营运能力分析指标。", subject: "财管", difficulty: "basic", type: "multiple" },
  { id: 342, point: "财务分析", q: "下列属于偿债能力指标的有（　）。", options: ["流动比率", "资产负债率", "利息保障倍数", "存货周转率"], answer: [0, 1, 2], explain: "流动比率反映短期偿债能力，资产负债率和利息保障倍数反映长期偿债能力；存货周转率衡量营运能力。", subject: "财管", difficulty: "basic", type: "multiple" },
  { id: 343, point: "增值税", q: "下列适用增值税 9% 低税率的项目包括（　）。", options: ["图书", "暖气", "食用植物油", "现代服务"], answer: [0, 1, 2], explain: "图书、暖气、食用植物油等适用 9% 低税率；现代服务一般适用 6% 税率。", subject: "税法", difficulty: "advanced", type: "multiple" },
  { id: 344, point: "企业所得税", q: "下列支出在计算企业所得税时不得税前扣除的有（　）。", options: ["向投资者支付的股息", "企业所得税税款", "违反法律的行政罚款", "符合条件的公益性捐赠"], answer: [0, 1, 2], explain: "向投资者支付的股息、企业所得税税款和违法行政罚款不得税前扣除；符合条件的公益性捐赠可以按规定限额扣除。", subject: "税法", difficulty: "advanced", type: "multiple" },
  { id: 345, point: "公司法", q: "依据现行公司法，下列属于有限责任公司股东会特别决议事项的有（　）。", options: ["修改公司章程", "增加或者减少注册资本", "公司合并、分立、解散", "选举非职工代表董事"], answer: [0, 1, 2], explain: "修改章程、增减注册资本、合并分立解散等重大事项须经特别决议；选举非职工代表董事通常属于普通决议事项。", subject: "经济法", difficulty: "advanced", type: "multiple" },
  { id: 346, point: "证券法", q: "下列属于上市公司重大事件并应及时披露的有（　）。", options: ["公司经营方针和经营范围的重大变化", "重大投资行为", "订立可能对资产、负债、权益产生重大影响的合同", "公司日常办公用品采购"], answer: [0, 1, 2], explain: "经营方针重大变化、重大投资和重要合同属于应当披露的重大事件；日常小额采购不构成重大事件。", subject: "经济法", difficulty: "basic", type: "multiple" },
  { id: 347, point: "公司战略类型", q: "下列属于发展战略类型的有（　）。", options: ["一体化战略", "密集型战略", "多元化战略", "收缩型战略"], answer: [0, 1, 2], explain: "发展战略主要包括一体化战略、密集型战略和多元化战略；收缩型战略属于防御性战略。", subject: "战略", difficulty: "advanced", type: "multiple" },
  { id: 348, point: "并购战略", q: "下列属于企业并购动机的有（　）。", options: ["获取协同效应", "提升市场支配力", "进入新市场", "任何多元化并购都能降低风险"], answer: [0, 1, 2], explain: "协同效应、市场支配力和进入新市场是常见并购动机；并购并不必然降低风险，多元化可能带来新的风险。", subject: "战略", difficulty: "advanced", type: "multiple" }
];
